config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :adresses
  resources :comments
  resources :ratings, only: :update
  resources :hotels

  devise_for :users
  resources :users

  root :to => "home#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/adress.rb
class Adress < ActiveRecord::Base
  validates :country, :state, :city, :street, presence: :true
  belongs_to :hotel

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_name, :body, presence: true, uniqueness: true
  belongs_to :hotel
  belongs_to :user
  has_one :rating, dependent: :destroy
  accepts_nested_attributes_for :rating
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  is_impressionable :column_name => :review, :unique => :request_hash, :counter_cache => true
  enum status: [:pending, :approved, :rejected]
  validate :status_workflow, if: :status_changed?
  validates :title, :description, :photo, :price, presence: true
  validates :title, :description, uniqueness: true
#   validates :photo, allow_blank: true, format: {
#                               with: %r{\.(gif|jpg|png)\Z}i,
#                               message: 'must be a URL for GIF, JPG or PNG image.'
# }
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  has_many :comments
  has_many :ratings
  has_one :adress
  accepts_nested_attributes_for :adress
  after_update :send_status

  def status_workflow
    errors.add(:status, 'must be pending before approved') if status == 'approved' && status_was != 'pending'
    errors.add(:status, 'must be pending before rejected') if status == 'rejected' && status_was != 'pending'
  end

  def send_status
    if status_changed?
      StatusNotifier.send_mail(self).deliver
    end
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user
  belongs_to :comment
  after_save :average_score

  def average_score
    hotel.update({rating: Rating.where(hotel: hotel).average(:score)})
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :hotels
has_many :comments
has_many :ratings

end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController

  def create
    @adress = Adress.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress }
      end
    end
  end

private

  def adress_params
    params.require(:adress).permit(:country, :state, :city, :street, :hotel_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.hotel }
      else
        format.html { redirect_to @comment.hotel }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:user_name, :body, :hotel_id, :user_id, rating_attributes: [:score, :comment_id, :user_id, :hotel_id]).merge(user: current_user)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hotels = Hotel.order('rating DESC').limit(5).includes(:comments)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  impressionist actions: [:show]
  before_action :set_hotel, only: [:show, :update]
  before_action :authenticate_user!, only: [:show, :new]

  def index
    @hotels = Hotel.all
  end

  def show
    @comments = @hotel.comments.all
    @comment = @hotel.comments.build
    @rating = Rating.new(user: current_user, hotel: @hotel, comment: @comment, score: 5)
  end

  def new
    @hotel = Hotel.new
    @hotel.adress ||= Adress.new
  end

  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      end
    end
  end


  private

  def set_hotel
    @hotel = Hotel.find(params[:id])
  end

  def hotel_params
    params.require(:hotel).permit(:title, :description, :photo, :price, :rating, :review, :user_id, :breakfast, adress_attributes: [:country, :state, :city, :street, :hotel_id]).merge(user: current_user)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to :back, notice: 'Rating was successfully created.' }
      end
    end
  end


private
  def rating_params
    params.require(:rating).permit(:score, :hotel_id, :comment_id).merge(user: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.haml
= simple_form_for @comment do |f|
  = f.error_notification
  .form-inputs
    = f.input :user_name, label: false, placeholder: 'Name (required field)'
    = f.input :body, placeholder: 'Please, leave your comment', label: false, :input_html => { :rows => 6 }
    = f.hidden_field :hotel_id
    = f.hidden_field :user_id
    = f.simple_fields_for :rating, @comment.rating do |p|
      = p.input :hotel_id, as: :hidden
      = p.input :user_id, as: :hidden
      = p.input :comment_id, as: :hidden
      = p.input :score, as: :select, collection: (1..5).to_a, label: 'Rate', include_blank: false
  .form-actions
    = f.button :submit

app/views/home/index.html.haml
%h1 Top rated hotels
.container
  - @hotels.each do |hotel|
    .title
      %h3= link_to hotel.title, hotel
    %h4
      .rating{:data_score => "#{hotel.rating}"}Rating:
    .hotel
      = image_tag hotel.photo_url(:thumb) if hotel.photo.present?
    .one
      %h3 Comments
      - hotel.comments.each do |comment|
        %strong= comment.user_name
        %br
        %p= truncate(strip_tags(comment.body), length:100)
      %p{:style=>"clear:left"}

:javascript
  $('.rating').raty({
    readOnly: true,
    path: '/img',
    score: function(){
      return $(this).attr('data_score');
    }
  });

app/views/hotels/_form.html.haml
= simple_form_for(@hotel) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.hidden_field :user_id
    = f.input :description, :input_html => { :rows => 6 }
    = f.input :price, as: :string, :input_html => {value: number_with_precision(f.object.price, precision: 2) }, :hint => "prices should be in USD"
    = f.input :breakfast, :as => :boolean, inline_label: 'Breakfast included? (yes/no)', label: false
    = f.input :photo
    = f.simple_fields_for :adress, @hotel.adress do |p|
      = p.input :country, as: :country
      = p.input :state
      = p.input :city
      = p.input :street
      = p.hidden_field :hotel_id
  .form-actions
    = f.button :submit

app/views/hotels/index.html.haml
%h1 Listing hotels
= link_to 'Add Hotel', new_hotel_path, :class => "btn btn-primary", id: "top_hotel"
.content
  - @hotels.each do |hotel|
    %h3= link_to hotel.title, hotel
    .hotel
      = image_tag hotel.photo_url(:thumb) if hotel.photo.present?
    .one
      %h3 Description:
      = hotel.description
    .break
      %label Breakfast:
      = hotel.breakfast ? 'yes' : 'no'
    .price_line
      %label Price:
      %span{:class=>"price"}#{number_to_currency(hotel.price)}|per_day
    %p{:style=>"clear:left"}

  = link_to 'Add Hotel', new_hotel_path, :class => "btn btn-primary", id: "new_hotel"

app/views/hotels/new.html.haml
%h1 New hotel

= render 'form'

= link_to 'Back', hotels_path, :class => "btn btn-success"

app/views/hotels/show.html.haml
.content
  %h4>
    %strong= @hotel.title
  = image_tag(@hotel.photo_url, :width => "60%") if @hotel.photo.present?
  .description
    %h4
      %b Description:
    = @hotel.description
  .break
    %label Breakfast included:
    = @hotel.breakfast ? 'yes' : 'no'
    %br
    %label Price:
    %span{:class=>"price"}#{number_to_currency(@hotel.price)}|per_day
  %h4
    %strong{:style=>"color:brown"} Address
  %label Country:
  = @hotel.adress.country
  %br
  %label State:
  %span= @hotel.adress.state
  %br
  %label City:
  %span= @hotel.adress.city
  %br
  %label Street:
  %span= @hotel.adress.street
  %h4
    %strong Comments
  - @comments.each do |comment|
    %h5{:style=>"color:blue"}
      %strong= comment.user_name
    %p= comment.body
    %b
      .rating{:data_score=>"#{comment.rating.score}"}Rate:
    %p
  %h4{:style=>"margin-top:20px"}
    %b Leave your comment, please
  = render 'comments/form'
  = link_to 'Back', hotels_path, :class => "btn btn-success"
  = "#{@hotel.review} views so far!"

:javascript
  $('.rating').raty({
    readOnly: true,
    path: '/img',
    score: function(){
      return $(this).attr('data_score');
    }
  });

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Advisor
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    %link{:rel=>"stylesheet", :href=>"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"}
    %link{:rel=>"stylesheet", :href=>"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css"}
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav{:class=>"nav navbar-inverse navbar-fixed-top", :role => "navigation", :width=>"100%"}
      %ul{:class=>"nav nav-tabs"}
        %li{:class=>"#{'active' if current_page?(root_path)}"}
          = link_to "Advisor", root_path
        %li{:class=>"#{'active' if current_page?(hotels_path)}"}
          = link_to "Hotels", hotels_path
        %ul{:class=>"nav navbar-nav navbar-right"}
          - if user_signed_in?
            #right-nav
              %span{:id=>"text"}Logged in as
              %strong{:id=>"text"}= current_user.email
              = link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-default navbar-btn" |
              %button{:type=>"button", :class=>"btn btn-default navbar-btn"}Sign in
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-default navbar-btn'
          - else
            #right-nav
              = link_to "Sign up", new_user_registration_path, :class => 'btn btn-default navbar-btn' |
              = link_to "Login", new_user_session_path, :class => 'btn btn-default navbar-btn'
    .container
      - if notice
        %p{:class=>"alert alert-success"}= notice
      - if alert
        %p{:class=>"alert alert-danger"}= alert
      = yield

app/views/status_notifier/send_mail.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<h2>Notification status</h2>
<p>This email was sent out to you, because your hotel <b><%= @hotel.title %></b> status is changed to <b><%= @hotel.status %></b>. Your hotel was added at <%= @hotel.created_at %></p>
<%= link_to "View your hotel", hotel_path(@hotel, only_path: false) %>